### ISSUE TITLE
Compiling ParcelsRandom Multiple times

### ISSUE THREAD

**Issue by axnsantana** [OceanParcels/parcels#1023]
Hi,

I am building a python package that internally uses Parcels, but I am facing a problem. Even though I do not use the part related to Parcel, I still get the compilation of the Parcels Random generator.
`INFO: Compiled ParcelsRandom ==> /tmp/parcels-1000/libparcels_random_0ad87ac4-bed2-4038-ad8c-8bd52cdace77.so`

https://github.com/OceanParcels/parcels/blob/400abb4a1335a1bdc8b0bfeb5e764ecfe452e70e/parcels/rng.py#L128

In some cases, when I make use of Joblib in any part of the package, I get the compilation N times the number of jobs I started with joblib. Jobs not correlated with Parcels.

I am using python 3.8.5 and Parcels 2.2.2.
Any suggestion to avoid this?

A minimal example:
```
# -*- coding: UTF-8 -*-

"""Package __init__ file."""

from . import module_a
from . import module_b

__all__ = ['module_a', 'module_b']
```

module_a.py
```
def mysum(a, b):
    print(F"a + b = {a+b}")
```
module_b.py
```
import parcels
from parcels import FieldSet, ParticleSet, ErrorCode
```
Executing:
```
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import use_case_parcels_issue as parcels_issue
INFO: Compiled ParcelsRandom ==> /tmp/parcels-1000/libparcels_random_65fdc468-557a-49ae-83aa-0e6ba384c19f.so
>>> parcels_issue.module_a.mysum(3,4)
a + b = 7
```

**Comment by axnsantana** [comment]
Here is the parallel example using joblib, N = 5 times compiled without uses parcels:

```
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from joblib import Parallel, delayed
>>> import use_case_parcels_issue as parcels_issue
INFO: Compiled ParcelsRandom ==> /tmp/parcels-1000/libparcels_random_97ee78cf-56ef-4d8c-b1db-f6473b321377.so
>>> parallel_sum = Parallel(n_jobs=5)(delayed(parcels_issue.module_a.mysum)(a,b) for a, b in zip(range(10),range(10,20)))
INFO: Compiled ParcelsRandom ==> /tmp/parcels-1000/libparcels_random_1d91a2aa-4d43-454d-80da-3f91d0005374.so
INFO: Compiled ParcelsRandom ==> /tmp/parcels-1000/libparcels_random_9dd3f403-bb60-4f7c-acd8-dad0effc0a7f.so
a + b = 10
a + b = 12
a + b = 20
a + b = 22
a + b = 24
a + b = 26
a + b = 28
INFO: Compiled ParcelsRandom ==> /tmp/parcels-1000/libparcels_random_1e00d4c3-b704-481c-8687-94deba551e7a.so
a + b = 14
INFO: Compiled ParcelsRandom ==> /tmp/parcels-1000/libparcels_random_b32b9dc7-32ca-41e7-a678-76d2c915fc0d.so
a + b = 16
INFO: Compiled ParcelsRandom ==> /tmp/parcels-1000/libparcels_random_0ccf3f1e-c50f-40a1-8065-eea99aff92da.so
a + b = 18
>>> 
```

**Comment by CKehl** [comment]
Hi @axnsantana ,

We discussed your issue today in our Dev meeting. Now, for multi-library compilation, we currently do compile the library on import, and we will attempt to change that again (no promises on that one though due to multi-pass compilation procedures). 

That said, another observation is that you use the _joblib_ for parallel processing. Now, for resource reasons I would advise against it. For parallel forcessing, parcels works within an MPI environment (or: is built to do that), so the suggestion is to install _mpi4py_ locally (e.g. via conda-forge) and use the MPI facilities that are there to reduce the memory footprint. This is though just a well-meant advice or suggestion.

Kind Regards,

@CKehl

**Comment by axnsantana** [comment]
Hi @CKehl, thank you for the time to look and discuss the issue. 

About the joblib, I do not use it with Parcels. I use it in another part of my package. It is a relatively simple calculation and joblib quite straightforwardly resolves it. To avoid multiple compilations, I changed the joblib backend to use threads (also more efficient) instead of the default loky. The loky backend starts multiples python workers, which means new imports and new Parcels_Random compilations.

best regards

**Comment by erikvansebille** [comment]
This should now be fixed in #1044

**Comment by CKehl** [comment]
partially fixed, but as much to the degree we can help you. If you run multiple worker processes (be it via the `joblib` module), then each process will once create this compiled library, but that is as it should be. That said, the library compilation won't be just started when importing parcels, but when calling the RNG for the first time in each instance. That is the kind of behaviour one can expect to happen. 
Using the RNG in a multi-threaded environment though does not guarantee randomized samples, as threaded calls to the library are out-of-sync. In other words: I'd expect each thread to receive the same RNG sequence, so the first/second/n-th sample of each thread will give you the same number. Parcels is not designed for a multi-threaded environment due to the communications issues required to address there. Just a word of caution.

Cheers, Christian
