### ISSUE TITLE
keyError when trying to sampling velocity 

### ISSUE THREAD

**Issue by slawchune** [OceanParcels/parcels#1172]
Hi Eric and co-workers, 

I encounter an issue that I can't solve. I Try to do a basic velocity sampling, but fall on a error. Here is the behaviour (I have successfully loaded my fieldset and initial (lon,lat,time) of my pset): 

```
def Sample_Velocity(particle, fieldset, time):
    # sample velocity in m/s instead of m/s 
    particle.U = fieldset.U.eval(time, particle.depth, particle.lat, particle.lon, applyConversion=False)
    particle.V = fieldset.V.eval(time, particle.depth, particle.lat, particle.lon, applyConversion=False)

class SampleParticle(JITParticle):         # Define a new particle class
    U = Variable('U', initial=0, to_write=True)
    V = Variable('V', initial=0, to_write=True)

# initialise the set of particle in Parcels kernel
pset = ParticleSet(fieldset=fieldset, pclass=SampleParticle,
                      lon=launch_lon, lat=launch_lat, time=launch_date)

ksample_UV = pset.Kernel(Sample_Velocity)    # Casting the Sample_UV function to a kernel.
pset.execute(ksample_UV, dt=0) # by only executing the sample kernel we record the initial UV of the particle

```

at the execution: 

```

In [63]:     pset.execute(ksample_UV, dt=0) # by only executing the sample kernel we
    ...: 
---------------------------------------------------------------------------
KernelError                               Traceback (most recent call last)
Input In [63], in <cell line: 1>()
----> 1 pset.execute(ksample_UV, dt=0)

File ~/.conda/envs/py3_parcels/lib/python3.10/site-packages/parcels/particleset/baseparticleset.py:458, in BaseParticleSet.execute(self, pyfunc, pyfunc_inter, endtime, runtime, dt, moviedt, recovery, output_file, movie_background_field, verbose_progress, postIterationCallbacks, callbackdt)
    456 # If we don't perform interaction, only execute the normal kernel efficiently.
    457 if self.interaction_kernel is None:
--> 458     self.kernel.execute(self, endtime=next_time, dt=dt, recovery=recovery, output_file=output_file,
    459                         execute_once=execute_once)
    460 # Interaction: interleave the interaction and non-interaction kernel for each time step.
    461 # E.g. Inter -> Normal -> Inter -> Normal if endtime-time == 2*dt
    462 else:
    463     cur_time = time

File ~/.conda/envs/py3_parcels/lib/python3.10/site-packages/parcels/kernel/kernelsoa.py:227, in KernelSOA.execute(self, pset, endtime, dt, recovery, output_file, execute_once)
    225 recovery_kernel = recovery_map[p.state]
    226 p.set_state(StateCode.Success)
--> 227 recovery_kernel(p, self.fieldset, p.time)
    228 if p.isComputed():
    229     p.reset_state()

File ~/.conda/envs/py3_parcels/lib/python3.10/site-packages/parcels/tools/statuscodes.py:121, in recovery_kernel_error(particle, fieldset, time)
    119 """Default error kernel that throws exception"""
    120 msg = "Error: %s" % particle.exception if particle.exception else None
--> 121 raise KernelError(particle, fieldset=fieldset, msg=msg)

KernelError: 0
Particle P[0](lon=-35.350231, lat=-17.763300, depth=0.000000, U=0.000000, V=0.000000, time=135000.000000)
Time: 2018-01-24T14:00:00.000000000,	timestep dt: -0.000000
```

Something went wrong, but if I try to execute what the kernel does in command lines what the kernel was supposed to do, it seems to work

```
In [70]: particle=pset ; time=0 ; 

In [71]: particle.U
Out[71]: 0

In [72]: particle.V
Out[72]: 0

In [73]: particle.U = fieldset.U.eval(time, particle.depth, particle.lat, parti)
    ...:     particle.V = fieldset.V.eval(time, particle.depth, particle.lat, parti)
    ...: 

In [74]: particle.U
Out[74]: array([-0.18082947], dtype=float32)

In [75]: particle.V
Out[75]: array([-0.07143945], dtype=float32)
```

Kind regards,
Stéphane

**Comment by slawchune** [comment]
Ok I think I got some infos there : https://nbviewer.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_jit_vs_scipy.ipynb ;)

**Comment by erikvansebille** [comment]
Yes indeed, that tutorial shows that Scipy-mode is a bit more robust (because needs no compilation) but _much_ slower than JIT-mode. So it would not be useful for production runs, I reckon.

I am really confused why you get this error. Which version of Parcels are you using? I thought we had by now fixed all `KernelErrors`...

**Comment by slawchune** [comment]
Hi Eric I use his one : 

# Name                    Version                   Build  Channel
parcels                   2.3.0            py38h578d9bd_2    conda-forge

It's not really a big deal for me using scipy mode, I don't loose a lot time computation : I do one particle, 3-day forecasts simulations.

**Comment by erikvansebille** [comment]
Hi @slawchune, I had a look again at your code above, but for me it works. Of course, I don't know what your fieldset and launch-location were, but the code below works as expected
```python
from parcels import JITParticle, FieldSet, ParticleSet, Variable

fieldset = FieldSet.from_data({'U': 1, 'V': 2}, {'lon': 0, 'lat': 0}, mesh='spherical')

def Sample_Velocity(particle, fieldset, time):
    # sample velocity in m/s instead of deg/s
    particle.U = fieldset.U.eval(time, particle.depth, particle.lat, particle.lon, applyConversion=False)
    particle.V = fieldset.V.eval(time, particle.depth, particle.lat, particle.lon, applyConversion=False)

class SampleParticle(JITParticle):
    U = Variable('U', initial=0, to_write=True)
    V = Variable('V', initial=0, to_write=True)

pset = ParticleSet(fieldset=fieldset, pclass=SampleParticle, lon=0, lat=0, time=0)

ksample_UV = pset.Kernel(Sample_Velocity)
pset.execute(ksample_UV, dt=0)

print(pset)
```
Could you check if this gives you the same Kernel Error as you reported before? Otherwise, it has something to do with your FieldSet and/or launch-locations?

**Comment by slawchune** [comment]
Hi Eric, 

Thanks for digging. No issue is encouter from my side when I execute your code above. 

I tried to look at the Fieldset, but I don't see anything weird. 

When you have some time, coud you please retrieve and test one excerpt of my code ? 

"ftp ftp.mercator-ocean.fr" with anonymous login

"cd /download/users/slawchune/evansebille"

You will find a SMOC file used to sett the fieldset, and a simple script leading to the issue.

Thanks again :) 
Stéphane

**Comment by erikvansebille** [comment]
Thanks @slawchune, for sharing this file and script. After some debugging, I found that the issue seems to stem from your use of `interp_method={'U': 'freeslip', 'V': 'freeslip'}` in the FieldSet creation. If you remove that part, it does seem to work...

The question now of course is: why? I'll dig into that more in the coming days, but it seems that there's an issue in the freeslip interpolation code in [`parcels.h`](https://github.com/OceanParcels/parcels/blob/master/parcels/include/parcels.h#L917-L985)

**Comment by slawchune** [comment]
Hi Eric and many thanks. 

I think I'll just wait that the fix/branch goes into the master :) (and keep the scipy mode in the meantime)

**Comment by erikvansebille** [comment]
Well, the code above, sampling `fieldset.U` and `fields.V` separately, is in general wrong. There is no guarantee that the sampled velocities are the same as the ones that are used in the advection. This is especially not guaranteed on Curvilinear Grids and when using special boundary conditions. See also the info in #1175. So I strongly recommend you use the Kernel below instead (works only in Scipy on the current `master`, but will also work in JIT once #1175 is merged)
```python
def Sample_Velocity(particle, fieldset, time):
    # sample velocity in m/s instead of deg/s
    particle.U, particle.V = fieldset.UV.eval(time, particle.depth, particle.lat, particle.lon, applyConversion=False)
```

**Comment by slawchune** [comment]
Ok thanks Eric, glad you saw my mistake !

**Comment by erikvansebille** [comment]
This has now been fixed in #1175

**Comment by slawchune** [comment]
Hi Eric, 

I fall an other issue with velocity sampling with summed fieldsets. The method eval doesn"t exist for this class :


`AttributeError: 'SummedVectorFieldNode' object has no attribute 'eval' `

Does it sound familiar ? 

Cheers,
Stéphane

**Comment by erikvansebille** [comment]
It should have been implemented in #1175; see also the code at https://github.com/OceanParcels/parcels/pull/1175/files#diff-2625537800ca3719e70d5e43e213f3ca585c292625346d948ca7d1d56c2a5e48R429-R448

**Comment by slawchune** [comment]
I've just checked this github revision and my Parcels sources.  I confirm that I have these modifications and it doesn't work : / 

# packages in environment at /home/ext/mr/smer/lawchunes/.conda/envs/py3_parcels:
parcels                   2.3.1.dev239+g31f81d5          pypi_0    pypi

Could you confirm me that it work on your side please Eric ?

**Comment by slawchune** [comment]
Hi Eric, 

Could you please try this code: Bug_Kernel_sampling_Summed_fields_SMOC.py 

"ftp ftp.mercator-ocean.fr" with anonymous login

"cd /download/users/slawchune/evansebille"

Thanks :)

**Comment by erikvansebille** [comment]
Thanks for providing the script. Indeed, I had forgotten to implement the sampling with `.eval()` for SummedVectorFields too. This is now fixed in #1200. Could you check if this PR works for you?

**Comment by slawchune** [comment]
Hi Eric, I've made the update (Successfully installed parcels-2.3.2.dev37)

but it still doesn't work, with the same error message than previously.  

Ps: I have also a weird git message when importing parcels, its not blocking though.  

```
(py3_parcels) [lawchunes@belenoslogin0:/scratch/work/lawchunes/Validation_SMOC/bug_evansebille]$ python
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import parcels
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
>>> print (parcels.__version__)
2.3.2.dev30+g0397a4e
```

**Comment by erikvansebille** [comment]
The PR hasn't been merged yet, so you will need to change branch in order to check if the new code works. Could that be why the error hasn't disappeared?
